#!/usr/bin/env python3
"""Validate the catalogue contract and generate its human-readable views."""

from __future__ import annotations

import argparse
from collections import Counter

import yaml

from catalogue_config import (
    DESIGN_PATH,
    GUIDE_PATH,
    SUMMARY_PATH,
    fail_on_errors,
    load_registry,
    load_rules,
    load_taxonomy,
    taxonomy_index,
    validate_registry,
    validate_taxonomy,
)


def load_family_colours() -> dict:
    text = DESIGN_PATH.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{DESIGN_PATH}: missing YAML frontmatter")
    frontmatter = yaml.safe_load(text.split("---\n", 2)[1])
    return frontmatter.get("familyColors") or {}


def validate_design(taxonomy: dict) -> list[str]:
    colours = load_family_colours()
    families = [family["slug"] for family in taxonomy["families"]]
    errors = []
    if set(colours) != set(families):
        errors.append("DESIGN.md familyColors must contain exactly the taxonomy family slugs")
    for slug, values in colours.items():
        if set(values) != {"hue", "chromaK"}:
            errors.append(f"DESIGN.md familyColors.{slug} must contain hue and chromaK only")
        elif not 0 <= values["chromaK"] <= 1:
            errors.append(f"DESIGN.md familyColors.{slug}.chromaK must be between zero and one")
    return errors


def guide_text(taxonomy: dict, rules: dict, members: list[dict]) -> str:
    index = taxonomy_index(taxonomy)
    counts = Counter(member["category"] for member in members)
    lines = [
        "<!-- Generated by SKILL/scripts/validate_catalogue.py. Do not hand-edit. -->",
        "# Company category classification rules",
        "",
        f"Taxonomy version: **{taxonomy['version']}**  ",
        f"Rules version: **{rules['version']}**",
        "",
        "## Classification principle",
        "",
        rules["principle"],
        "",
        "A company receives one primary category. Its high-level family is derived from that category.",
        "",
        "## Publication requirements",
        "",
    ]
    lines.extend(f"- {item}" for item in rules["publication_requirements"])
    lines += ["", "## Evidence priority", ""]
    lines.extend(f"{number}. {item}" for number, item in enumerate(rules["evidence_priority"], 1))
    lines += ["", "## Family decision sequence", ""]
    for number, row in enumerate(rules["family_sequence"], 1):
        family = index["family_by_slug"][row["family_slug"]]
        lines.append(f"{number}. **{family['en']} — {family['fi']}**: {row['question']}")
    lines += ["", "## Category decision sequences", ""]
    for family_rules in rules["families"]:
        family = index["family_by_slug"][family_rules["family_slug"]]
        lines += [
            f"### {family['en']} — {family['fi']}",
            "",
            f"{family['description_en']}  ",
            family["description_fi"],
            "",
        ]
        for number, rule in enumerate(family_rules["rules"], 1):
            category = index["category_by_slug"][rule["category_slug"]]
            lines += [
                f"{number}. **{category['en']} — {category['fi']}** ({counts[category['slug']]} companies)",
                f"   - Question: {rule['question']}",
                f"   - Includes: {', '.join(rule['includes'])}.",
                f"   - Excludes: {', '.join(rule['excludes'])}.",
                f"   - Description: {category['description_en']}",
                f"   - Kuvaus: {category['description_fi']}",
            ]
        lines.append("")
    lines += ["## Tie-break rules", ""]
    lines.extend(f"- {item}" for item in rules["tie_breakers"])
    lines += ["", "## Representative validation", "", "A company representative should confirm that:", ""]
    lines += [
        "- the category describes the company’s dominant role in this ecosystem;",
        "- the category does not imply services or products the company does not provide;",
        "- a more specific category is not clearly applicable; and",
        "- any claimed Finnish main-contractor role is supported by a project reference.",
        "",
    ]
    return "\n".join(lines)


def summary_text(taxonomy: dict, members: list[dict]) -> str:
    counts = Counter(member["category"] for member in members)
    lines = [
        "<!-- Generated by SKILL/scripts/validate_catalogue.py. Do not hand-edit. -->",
        "# Category summary",
        "",
        f"Taxonomy version: **{taxonomy['version']}**  ",
        f"Companies: **{len(members)}**",
        "",
        "| Family | Category | Kategoria | Description | Kuvaus | Companies |",
        "|---|---|---|---|---|---:|",
    ]
    for family in taxonomy["families"]:
        for category in family["categories"]:
            lines.append(
                f"| {family['en']} | {category['en']} | {category['fi']} | "
                f"{category['description_en']} | {category['description_fi']} | {counts[category['slug']]} |"
            )
    lines += ["", f"**Total: {sum(counts.values())}**", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated files without writing")
    parser.add_argument(
        "--allow-uncategorised",
        action="store_true",
        help="allow temporary intake records; never use for a publication build",
    )
    args = parser.parse_args()

    taxonomy = load_taxonomy()
    rules = load_rules()
    members = load_registry()
    errors = validate_taxonomy(taxonomy, rules)
    errors += validate_design(taxonomy)
    errors += validate_registry(members, taxonomy, publish=not args.allow_uncategorised)
    fail_on_errors(errors)

    generated = {
        GUIDE_PATH: guide_text(taxonomy, rules, members),
        SUMMARY_PATH: summary_text(taxonomy, members),
    }
    if args.check:
        drift = [str(path) for path, expected in generated.items() if not path.exists() or path.read_text(encoding="utf-8") != expected]
        fail_on_errors([f"generated file is stale: {path}" for path in drift])
        print(f"Validated taxonomy {taxonomy['version']}, rules {rules['version']}, {len(members)} companies, and generated files.")
        return

    SUMMARY_PATH.parent.mkdir(exist_ok=True)
    for path, text in generated.items():
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path}")
    print(f"Validated taxonomy {taxonomy['version']}, rules {rules['version']}, and {len(members)} companies.")


if __name__ == "__main__":
    main()
